-- GOH 20-client roster load. Source: goh_client_intake_mapping.md (2026-06-29).
-- Safe to re-run: upsert on name. REQUIRES migration 0016 (unique index on name).
-- "unknown" values load AS-IS (the USASpending lookup fires on "unknown" by design).
-- Non-schema fields (legal_name, entity_subtype, uei, profile_confidence) folded
-- into notes as labeled freetext.

insert into clients (
  name, org_type, status, engagement_tier, primary_contact_name, primary_contact_email,
  location_city, location_county, location_state, service_area, rucc_codes, annual_budget,
  primary_funding_needs, project_stage, match_cost_share_capacity, federal_grant_history,
  sam_uei_status, known_constraints, matching_rules, usaspending_search_name,
  federal_history_verified, notes
) values

-- 1. Arisa Health
('Arisa Health', 'nonprofit', 'active', 'build', 'Shadun Duncan', 'unknown',
 'Springdale', 'Washington County', 'AR',
 ARRAY['AR — 41 northern counties']::text[],
 'unknown — verify; Washington County likely RUCC 2 but serves rural counties',
 '~$15M+ (Medicaid-funded, self-sustaining; $4.4M reduction underway)',
 ARRAY['rural health transformation','behavioral health infrastructure / capital','telehealth','suicide prevention','care coordination / CHW','SUD residential','workforce development']::text[],
 'implementation', 'moderate — avoid heavy match; capital timelines often misalign', 'unknown',
 'unknown',
 'Supplanting risk: any scope touching formerly CMHC-funded service lines flagged under fund-replacement-restriction grants. $4.4M revenue reduction will appear in financials — capacity questions likely. Do not propose grants funding existing staff/roles. Avoid programs requiring extensive county judge/mayor letters. Not research-heavy. Medicaid-funded model.',
 'Capital grant timelines often misalign with construction schedules — prefer flexible or retroactive funding. Flag any grant with fund-replacement restriction before recommending. SAMHSA does not fund capital — do not surface SAMHSA capital plays. Sustainability framing must present activities as new or expanded, not replacement.',
 null, false,
 'Legal name: Arisa Health. Entity subtype: integrated behavioral and primary health provider. UEI: unknown. Profile confidence: partial.'),

-- 2. CACHE Creative
('CACHE Creative', 'nonprofit', 'active', 'build', 'Kelsey Howard', 'kelsey@cachecreate.org',
 'Springdale', 'Washington County', 'AR',
 ARRAY['AR — NWA (Springdale, Fayetteville, Bentonville, Rogers)','OK — Tulsa region']::text[],
 '2', '~$2.4M',
 ARRAY['revenue diversification','arts regranting / intermediary','artist residencies','professional development']::text[],
 'implementation', 'low — WFF/TFF expiring Dec 2026/Jan 2027; revenue cliff urgent', 'unknown',
 'unknown',
 'NEA avoidance: client prefers not to pursue NEA grants due to censorship concerns. RAO classification excludes CACHE from NEA GAP. AWF drafting rules: focus on artists not organization, no hyperlinks, no ecosystem framing. Do not conflate AWF Multi-Year Program Support with AWF RRP.',
 'Never surface NEA grants. RAO classification = explicitly excluded from NEA GAP. WFF never appears in any client-facing grant document. Prioritize foundation grants that fund artists directly.',
 null, false,
 'Legal name: CACHE Creative. Entity subtype: regional arts intermediary. UEI: unknown. Profile confidence: partial.'),

-- 3. Columbia County
('Columbia County', 'local_government', 'active', 'build', 'Emily Fields', 'unknown',
 'Magnolia', 'Columbia County', 'AR',
 ARRAY['AR — Columbia County (Magnolia, Waldo, Emerson, McNeil, Taylor)']::text[],
 'unknown — verify; likely rural (SW Arkansas)', 'unknown — ~$1M average annual grant acquisition',
 ARRAY['roads and bridges','county facilities / emergency center','historic preservation','asbestos abatement','emergency management / public safety']::text[],
 'ongoing_ops', 'low — prefers to avoid significant cash match; funds needed for roads', 'unknown',
 'unknown',
 'LMI thresholds have disqualified individual projects in the past. Programs frequently run out of funds before application is reached. Prefers minimal cash match.',
 'Flag any grant with significant match requirement before surfacing. LMI-dependent grants (CDBG) require project-specific LMI verification before recommending.',
 null, false,
 'Legal name: Columbia County, Arkansas. Entity subtype: county government. UEI: unknown. Profile confidence: partial.'),

-- 4. Community Clinic (St. Francis House NWA)
('Community Clinic', 'fqhc', 'active', 'build', 'Lisa Stafford', 'unknown',
 'Springdale', 'Washington County', 'AR',
 ARRAY['AR — Benton County','AR — Washington County']::text[],
 '2', 'unknown',
 ARRAY['behavioral health workforce','remote patient monitoring','capital expansion (dental, women''s health)','food / nutrition access']::text[],
 'implementation', 'low — limited capital reserves; prefer low/no match', 'confirmed H80 HRSA grantee',
 'unknown',
 'Benton and Washington counties are RUCC 2 — ineligible for grants requiring rural project activity. RHTP THRIVE ineligible on geography. Medicaid/Medicare billing dependent. Indirect costs not allowable on THRIVE.',
 'Hard block: do not surface any grant requiring rural project activity in Benton or Washington counties — RUCC 2 disqualifies.',
 'St. Francis House NWA, Inc.', false,
 'Legal name: St. Francis House NWA, Inc. Entity subtype: Federally Qualified Health Center — H80 HRSA grantee. UEI: unknown. Profile confidence: partial.'),

-- 5. EverHope
('EverHope', 'nonprofit', 'active', 'build', 'Sierra Cox', 'scox@everhope.org',
 'Bentonville', 'Benton County', 'AR',
 ARRAY['AR — statewide (only 27% from NWA)']::text[],
 'unknown — Bentonville likely RUCC 2; serves statewide', '~$500K',
 ARRAY['facilities and safety (HVAC, security, fire alarm)','vehicle','general operating support','youth aging out of care / Pathways to Adulthood (2027)']::text[],
 'implementation', 'high sensitivity — $500K budget; flag any significant match requirement',
 'Recently rebranded from Northwest Arkansas Children''s Shelter (NWACS) January 2026. Prior federal history exists under NWACS name — live USASpending lookup suppressed; verify manually via USASpending search on Northwest Arkansas Children''s Shelter.',
 'unknown',
 'Opted out of AR domestic violence shelter licensure — ineligible for state Domestic Violence Shelter Fund. Cannot safely house teens. Facility limits: single mothers with up to 2 children. Cautious on public funding due to prior admin burden. Grants lead is new — requires at least 30 days lead time before alerting.',
 'Never surface AR Domestic Violence Shelter Fund — opted out of licensure, ineligible. Flag any grant with match requirement >10% before surfacing. Minimum 30-day lead time required — do not alert on grants with <30 days to deadline.',
 null, true,
 'Legal name: EverHope (formerly Northwest Arkansas Children''s Shelter / NWACS). Rebranded January 2026; W-9 reissued February 2026. Entity subtype: youth and victim services, transitional housing. UEI: unknown. Profile confidence: partial.'),

-- 6. Faulkner County
('Faulkner County', 'local_government', 'active', 'build', 'Randy Higgins', 'randy.higgins@faulknercountyar.gov',
 'Conway', 'Faulkner County', 'AR',
 ARRAY['AR — Faulkner County (Conway, Greenbrier, Mayflower, Vilonia)']::text[],
 'unknown — Conway is a mid-size city; verify', 'unknown',
 ARRAY['document restoration and digitization','transportation infrastructure','public safety / OEM','community development (CDBG)','grant management capacity']::text[],
 'ongoing_ops', 'medium — no specific sensitivity noted; creative city/county models needed', 'unknown',
 'unknown',
 'Requires integrated city/county funding models. Must coordinate with MetroPlan and CAPDD. Contract venue updated to Faulkner County.',
 'Flag grants requiring standalone county application where city co-application would strengthen eligibility — recommend integrated model.',
 null, false,
 'Legal name: Faulkner County, Arkansas. Entity subtype: county government. UEI: unknown. Profile confidence: partial.'),

-- 7. Greene County
('Greene County', 'local_government', 'active', 'launch', 'Rusty A. McMillon', 'cojudge@greene.ar.gov',
 'Paragould', 'Greene County', 'AR',
 ARRAY['AR — Greene County']::text[],
 'unknown — verify; NE Arkansas, likely rural', 'unknown',
 ARRAY['roadway safety (SS4A)','infrastructure and hazard mitigation (FEMA BRIC)','general infrastructure and capital']::text[],
 'ongoing_ops', 'medium — SS4A 20% match noted as constraint; quorum court must approve', 'unknown',
 'unknown',
 'Quorum Court approval required for all match commitments — flag deadlines at least 6 weeks out. SS4A 20% match requirement. BRIC NOI deadline missed — follow up with ADEM on late submission.',
 'Flag any grant requiring match commitment — quorum court approval needed, 6-week lead minimum. Do not surface grants where quorum court cannot approve in time given deadline.',
 null, false,
 'Legal name: Greene County, Arkansas. Entity subtype: county government. UEI: unknown. Profile confidence: partial.'),

-- 8. Harbor House
('Harbor House', 'nonprofit', 'active', 'navigate', 'Carl G. Norris', 'cnorris@harborhouse.inc',
 'Fort Smith', 'Sebastian County', 'AR',
 ARRAY['AR — Fort Smith','AR — Hot Springs','AR — NWA (Rogers, Fayetteville, Russellville, Conway)']::text[],
 'unknown — Fort Smith is metro; verify', '~$15M',
 ARRAY['capital expansion — transitional living beds (124 to 200+)','brick and mortar construction only']::text[],
 'scaling', 'medium — operationally self-sustaining; challenge grant structures require matching commitment', 'unknown',
 'unknown',
 'Capital-focused only — not ideal for program-only grants. SAMHSA does not fund capital. Federal competitive grants require multi-month lead time. Funder sequencing: Shannon handles initial outreach, Carl looped in only after positive signal. Tyson Foundation requires plant-level chaplain vouch before pursuing.',
 'Program-only grants: do not surface unless capital component exists. SAMHSA: never surface for capital. Minimum 90-day lead time for federal competitive grants — do not alert on short-cycle federal without pre-positioning. Legal name for USASpending: verify ''Harbor House Inc.'' exact registered form.',
 null, false,
 'Legal name: Harbor House, Inc. Entity subtype: adult addiction recovery, integrated behavioral health. UEI: unknown. Profile confidence: partial.'),

-- 9. Havenwood
('Havenwood', 'nonprofit', 'active', 'build', 'Jim Evans', 'jime@nwahavenwood.org',
 'Bentonville', 'Benton County', 'AR',
 ARRAY['AR — Northwest Arkansas']::text[],
 'unknown — Bentonville likely RUCC 2', '~$500K',
 ARRAY['unrestricted operational support','therapist / counseling program','security system upgrades','legal assistance program','housing expansion']::text[],
 'ongoing_ops', 'high sensitivity — $500K budget', 'unknown',
 'unknown',
 'Opted out of AR domestic violence shelter licensure — ineligible for state Domestic Violence Shelter Fund. Facility limits: single mothers with up to 2 children; cannot safely house teens. Cautious on public funding. Board expects demonstrated new grant revenue.',
 'Never surface AR Domestic Violence Shelter Fund — opted out of licensure, ineligible. Flag any grant with significant match requirement before surfacing.',
 null, false,
 'Legal name: Havenwood. Entity subtype: domestic violence and family transitional housing. UEI: unknown. Profile confidence: partial.'),

-- 10. Mississippi County
('Mississippi County', 'local_government', 'active', 'build', 'Tammy Winstead', 'grant.director@mississippicountyar.org',
 'Blytheville', 'Mississippi County', 'AR',
 ARRAY['AR — Mississippi County (Blytheville, Osceola, Manila and surrounding Delta communities)']::text[],
 'unknown — Delta county; likely rural; verify', 'unknown',
 ARRAY['Arkansas Aeroplex redevelopment (Eaker AFB)','hangar construction (~$15M)','Building 231 adaptive reuse ($1.37M)','ARFF fire rescue truck (~$1.48M)','aviation workforce development','National Cold War Center (long horizon)']::text[],
 'implementation', 'low to medium — entire county is OZ; DRA SEDAP qualifies for 100% federal; flag match requirements; quorum court approval required (6-week lead)',
 '$2M Crawford appropriation (demolition); $1.2M Crawford appropriation (teardown/repurposing); $1M AEDC site development',
 'unknown',
 'Fully pivoted to Aeroplex — hospital work is closed. One-grant-at-a-time standalone alerts only. Quorum court approval for match: meets monthly, 6-week lead minimum. Congressional routes exhausted for Building 231 and ARFF truck — do not re-pursue. Runway is private use — AIP requires public-use designation. Galactic Air is for-profit — cannot be named recipient or subrecipient under any circumstances.',
 'HARD BLOCK: Galactic Air (for-profit) cannot appear as recipient or subrecipient on any grant recommended to this client. Do not re-pursue congressional appropriations for Building 231 or ARFF truck — exhausted. Flag any match commitment — quorum court approval required, 6-week minimum lead. Alerts must be standalone and actionable enough for Tammy to take to quorum court.',
 null, false,
 'Legal name: Mississippi County, Arkansas. Entity subtype: county government — Opportunity Zone designated. UEI: unknown. Profile confidence: partial.'),

-- 11. MSET
('MSET', 'nonprofit', 'active', 'build', 'Davis Pace', 'davis.pace@mset.org',
 'Stennis Space Center', 'Hancock County', 'MS',
 ARRAY['MS — statewide aerospace, defense, technology sectors']::text[],
 'unknown — verify Hancock County', 'unknown — facing ~$200K NASA funding loss in 2026',
 ARRAY['innovation accelerator / incubator development','commercialization of university research','revenue-generating infrastructure','workforce development']::text[],
 'planning', 'low — small admin team; grant strategies must cover overhead', 'unknown',
 'unknown',
 'Out-of-state (Mississippi). Prefers sub/partner roles to avoid competing with MDA and Innovate Mississippi. Small admin team — overhead coverage required in grant strategies. Mississippi is 49th in SBIR applications and 50th in awards.',
 'Prefer sub or co-applicant role recommendations — not prime on competitive awards where MDA or Innovate MS would compete. Ensure overhead coverage in any recommended grant. Out-of-state client — Arkansas-specific programs are not applicable.',
 null, false,
 'Legal name: Mississippi Technology Alliance / MSET. Entity subtype: technology transfer office — Mississippi official TTO. UEI: unknown. Profile confidence: partial.'),

-- 12. NWACC
('NWACC', 'higher_education', 'active', 'build', 'Kim Syverson', 'ksyverson@nwacc.edu',
 'Bentonville', 'Benton County', 'AR',
 ARRAY['AR — Benton County','AR — NWA region']::text[],
 '2', 'unknown',
 ARRAY['workforce development / short-term credentialing','student support systems (childcare, mental health, transportation, food)','STEM / advanced manufacturing equipment','generative AI and operational dashboards']::text[],
 'implementation', 'medium — confirm per-grant; match capacity unverified',
 'prior SIP award; prior FIPSE applications on file; CCAMPIS returning applicant',
 'unknown',
 'All communications must route through Kim Syverson — do not contact other staff directly. Not research-heavy; prefer applied and workforce-oriented grants. Walmart relationship: flag for conflict-of-interest screening. NWACC is partner only on Eagle Way transportation grants — never list as applicant or primary beneficiary.',
 'All alerts and outreach route through Kim Syverson only. Never list NWACC as applicant or primary beneficiary on Eagle Way / transportation grants — partner role only. WFF never appears in any client-facing grant document. Flag Walmart conflict-of-interest screening for any grant where Walmart Foundation or Walmart Inc. is involved.',
 null, false,
 'Legal name: NorthWest Arkansas Community College. Entity subtype: public two-year community college — HLC accredited. UEI: unknown. Profile confidence: partial.'),

-- 13. NWA Council / CareersNWA
('NWA Council', 'nonprofit', 'active', 'partner', 'Mike Harvey', 'mikeharvey@nwacouncil.org',
 'Springdale', 'Washington County', 'AR',
 ARRAY['AR — Benton County','AR — Washington County','AR — Madison County']::text[],
 '2', 'unknown — Single Audit triggered if federal expenditures exceed $750K',
 ARRAY['workforce development / talent (CareersNWA)','workforce housing (Groundwork NWA)','entrepreneurship (StartupNWA)','economic development (InvestNWA)','health care transformation (NWAC Health)','belonging and bridging (EngageNWA)','infrastructure and policy']::text[],
 'implementation', 'medium — no indirect cost rate elected; Single Audit threshold a consideration',
 'unknown — NWAC Health has no prior federal grant history',
 'unknown — verify active',
 'Benton/Washington/Madison are RUCC 2 — ineligible for rural-designated programs. NWAC cannot prime major federal infrastructure programs. EngageNWA is 100% WFF-funded. No indirect cost rate elected. Cross-cutting funders (WRF, J.B. Hunt, Simmons, Walmart) must be coordinated centrally. ARC POWER: Arkansas not eligible — hard cut. USDA RCDI: NWA metro adjacency exclusion.',
 'Hard block: ARC POWER — Arkansas ineligible. Hard block: USDA RCDI — NWA metro adjacency exclusion. Hard block: any rural-designated program — RUCC 2 across all three counties. WFF never appears in any workstream-level report or client-facing document. All cross-cutting funder pursuit (WRF, J.B. Hunt, Simmons, Walmart) must be coordinated centrally before any workstream submits independently. NWAC Health past performance: none — flag on any grant where federal prime history is scored.',
 null, false,
 'Legal name: NWA Council / NWAC Foundation. Entity subtype: regional convener — 7 workstream entities; 501(c)(3) foundation. UEI: UXTWG5AF9945. Profile confidence: confirmed.'),

-- 14. Ozark Regional Transit
('Ozark Regional Transit', 'transit_authority', 'active', 'launch', 'Joel Gardner', 'jgardner@ozark.org',
 'Springdale', 'Washington County', 'AR',
 ARRAY['AR — NWA region']::text[],
 '2', 'unknown',
 ARRAY['BUILD Transportation Grants Program','Bus and Bus Facilities Program','HOPE Program']::text[],
 'planning', 'unknown — verify', 'unknown',
 'unknown',
 'Contract governed by Arkansas law, venue in Benton County. Client will push scope boundaries — GRANTED has set precedent against free work. Work currently delayed pending payment. Kickoff call requires Shannon''s presence.',
 'Surface transit-specific federal programs only (FTA, BUILD, HOPE, Bus and Bus Facilities). Scope boundary rule: flag any request that exceeds contracted scope before acting.',
 null, false,
 'Legal name: Ozark Regional Transit Authority. Entity subtype: regional transit authority — public body. UEI: unknown. Profile confidence: partial.'),

-- 15. Pathway to Freedom
('Pathway to Freedom', 'nonprofit', 'active', 'build', 'Chad Crabill', 'unknown',
 'Wrightsville', 'Pulaski County', 'AR',
 ARRAY['AR — statewide (post-release)','AR — NWA (transitional housing expansion)']::text[],
 'unknown — Wrightsville/Pulaski County; verify', '~$618K (projected $700-750K next year)',
 ARRAY['reentry housing expansion in NWA (capital + program delivery)','Hawkins Unit program-space expansion (~$2.3M facility)','in-prison rehabilitation and reentry program delivery','vocational / workforce development']::text[],
 'scaling', 'medium — public grants may require match; one funder requires 40% non-government donors',
 'AG opioid-settlement ~$972K; Serving USA $60K/yr',
 'unknown',
 'Faith-based, Christ-centered — will not pursue grants that restrict or hamper religious mission; screen all grants for Establishment Clause and religious-activity restrictions. All-male program only. Cannot pursue new opioid-settlement funding until existing AG grant is closed out. Hawkins Unit expansion gated on DOC letters of support. Construction is priority but several funders do not fund construction.',
 'HARD SCREEN: before surfacing any grant, screen for Establishment Clause / religious-activity restrictions — faith-based mission is non-negotiable. Hard block: do not surface new opioid-settlement grants until AG grant is closed. All-male beneficiary scope — do not surface grants requiring gender-inclusive programming.',
 null, false,
 'Legal name: Pathway to Freedom, Inc. Entity subtype: faith-based prisoner reentry and rehabilitation — all-male program. UEI: unknown. Profile confidence: partial.'),

-- 16. Pope County
('Pope County', 'local_government', 'active', 'build', 'Ben Cross', 'popecountyjudge@popecountyar.gov',
 'Russellville', 'Pope County', 'AR',
 ARRAY['AR — Pope County and surrounding communities']::text[],
 'unknown — Russellville is a mid-size city; verify', 'unknown — no dedicated county sales tax since 1995',
 ARRAY['public safety and emergency response (911, drones, mobile command, radio)','infrastructure and facilities (bridges, extension facility, senior center, EMS facility)','technology (cybersecurity, digital network)','historic preservation (courthouse)']::text[],
 'ongoing_ops', 'low — no dedicated county sales tax since 1995; severely limits capital improvement funds',
 'Community Wildfire Defense Grant ($68K); BUILD Planning Grant (submitted)',
 'unknown',
 'No dedicated county sales tax since 1995 — match is a hard constraint. Census undercount (64K vs. est. 82K) leads to underfunding in formula programs. Not interested in low-income housing development or recreational grants. LMI challenges can be addressed by targeting specific block groups.',
 'Do not surface low-income housing development grants — client explicitly not interested. Do not surface recreational grants — not a priority. Flag any grant with significant match requirement. LMI-dependent grants require project-specific block-group targeting before recommending.',
 null, false,
 'Legal name: Pope County, Arkansas. Entity subtype: county government. UEI: unknown. Profile confidence: partial.'),

-- 17. RROK / Dunyasi Ventures
('RROK / Dunyasi Ventures', 'for_profit', 'active', 'flex', 'Meaghan Burns', 'meaghan@dunyasiventures.com',
 'Jones', 'Oklahoma County', 'OK',
 ARRAY['OK — OKC metro','OK — southeastern Oklahoma']::text[],
 'unknown — OKC metro; verify', 'under $100K',
 ARRAY['AI and workforce upskilling','remote-work job placement','sustaining funding beyond Dunyasi pilot']::text[],
 'planning', 'low — early stage; 40% match on EDA AI Upskill allowable as 100% in-kind', 'none',
 'unknown',
 'For-profit entity — cannot be prime or Lead Entity on any federal competitive award. Must sit under an eligible Lead Entity (SEOSU target, Rose State fallback). Staffing/placement-commission revenue model must be narratively separated from any grant scope. Independent evaluator required in budget. No prior grant history.',
 'HARD BLOCK: cannot be recommended as prime or co-applicant on any federal grant. Role ceiling: sub / program operator only. Staffing commission revenue must never appear entangled with grant scope in any recommended pursuit. Flag independent evaluator requirement on all federal applications.',
 null, false,
 'Legal name: Dunyasi Ventures (parent); Remote Ready OK (operating program). Entity subtype: for-profit workforce / AI upskilling program. UEI: unknown — cannot be federal prime. Profile confidence: partial.'),

-- 18. Saline County
('Saline County', 'local_government', 'active', 'build', 'Angie Drummond', 'angie.drummond@salinecounty.org',
 'Benton', 'Saline County', 'AR',
 ARRAY['AR — Saline County']::text[],
 'unknown — Benton is suburban; verify', 'unknown — population ~125K',
 ARRAY['Southwest Trail (active transportation, 65 miles)','intersection improvements','bridge replacement (Quapaw, Danville)','public safety','flood mitigation','rodeo arena / fairgrounds reconstruction']::text[],
 'implementation', 'medium — 80/20 and 90/10 comfortable; 60/40 on large capital is a stretch',
 'TAP, RTP, STBG (Metroplan), Byrne JAG, FEMA PA (2025 flood), prior BRIC award (never funded)',
 'unknown',
 'CDBG ineligible — population and income profile. County owns no street lights, sidewalks, or gutters — limits SS4A Implementation fit. SS4A eligible scope is Local Road Safety Plan development only. Double-dip risk on TAP: new award on same scope requires explicit ARDOT clearance. 60/40 match on large capital is a stretch.',
 'Hard block: CDBG — ineligible by population and income profile. SS4A: surface planning-only scope (Local Road Safety Plan) — not implementation or master road plan update. Flag any TAP application for double-dip risk against prior award. Do not surface any grant where 60/40 match is required on large capital without flagging.',
 null, false,
 'Legal name: Saline County, Arkansas. Entity subtype: county government — Metroplan MPO / CAPDD planning district. UEI: unknown. Profile confidence: partial.'),

-- 19. UAMS NorthWest
('UAMS NorthWest', 'higher_education', 'active', 'build', 'Ryan Cork', 'rcork@uams.edu',
 'Fayetteville', 'Washington County', 'AR',
 ARRAY['AR — Northwest Arkansas region','AR — Carroll County (RUCC 6)','AR — Boone County (RUCC 7)']::text[],
 '2', '~$2.2B (UAMS system)',
 ARRAY['GME expansion and workforce development in rural areas','psychiatry / behavioral health programs','nursing research','telehealth infrastructure','AI and health technology integration']::text[],
 'implementation', 'high — large institution; match generally not a constraint',
 'NIH/AR Tech-DaSH ($1.3M, 2024); HRSA/AHEC POSME renewal ($17.6M, 2023-2028); NIH COBRE/Maternal & Reproductive Community Health Excellence Center ($11.7M, 2025-2030) — campus-scoped history only; do not credit full UAMS system awards.',
 'unknown',
 'Washington County is RUCC 2 — rural eligibility ambiguity. Only Carroll (RUCC 6) and Boone (RUCC 7) are rural-eligible in the four-county footprint. For large research-heavy awards (R34s, K12s, PRIMED-AI), most realistic position is partner/regional hub under UAMS main campus — not prime. Outreach emails to Ryan Cork must never mention NWAC or NWA Council.',
 'Role ceiling on research-heavy mechanisms (R34, K12, PRIMED-AI): recommend partner or hub under UAMS main campus, not prime. Rural program eligibility: only Carroll and Boone counties qualify — do not use Washington County location as rural eligibility basis. HARD RULE: never mention NWA Council or NWAC in any outreach or document directed to Ryan Cork.',
 null, true,
 'Legal name: University of Arkansas for Medical Sciences — NorthWest Campus. Entity subtype: academic medical center / public university — GME anchor. UEI: unknown. Profile confidence: partial.'),

-- 20. WorkAbility Alliance
('WorkAbility Alliance', 'nonprofit', 'active', 'flex', 'Breann Ashford', 'unknown',
 'Siloam Springs', 'Benton County', 'AR',
 ARRAY['AR — rural service area (unverified)']::text[],
 'unknown — rural designation unverified; verification is first deliverable', 'unknown',
 ARRAY['workforce development and employment support']::text[],
 'planning', 'unknown', 'unknown',
 'unknown',
 'Rural designation must be confirmed before any USDA RBDG or rural-program pursuit. Building owned at 101 Broadway, Siloam Springs — flag for CDBG eligibility, match documentation, USDA program eligibility, and potential historic district / Main Street angles. Engagement is Flex ($1,000) — scope accordingly.',
 'Do not surface USDA rural programs until rural designation is confirmed. Building ownership at 101 Broadway: flag CDBG eligibility and USDA implications before recommending capital grants. Flex engagement — scope recommendations to match $1K engagement level.',
 null, false,
 'Legal name: WorkAbility Alliance. Entity subtype: workforce and employment support. UEI: unknown. Profile confidence: inferred.')

on conflict (name) do update set
  org_type                  = excluded.org_type,
  engagement_tier           = excluded.engagement_tier,
  primary_contact_name      = excluded.primary_contact_name,
  primary_contact_email     = excluded.primary_contact_email,
  location_city             = excluded.location_city,
  location_county           = excluded.location_county,
  location_state            = excluded.location_state,
  service_area              = excluded.service_area,
  rucc_codes                = excluded.rucc_codes,
  annual_budget             = excluded.annual_budget,
  primary_funding_needs     = excluded.primary_funding_needs,
  project_stage             = excluded.project_stage,
  match_cost_share_capacity = excluded.match_cost_share_capacity,
  federal_grant_history     = excluded.federal_grant_history,
  sam_uei_status            = excluded.sam_uei_status,
  known_constraints         = excluded.known_constraints,
  matching_rules            = excluded.matching_rules,
  usaspending_search_name   = excluded.usaspending_search_name,
  federal_history_verified  = excluded.federal_history_verified,
  notes                     = excluded.notes,
  updated_at                = now();
