-- Allowable uses of funds, per grant, quote-verified against the NOFO.
--
-- WHAT THIS IS. A short list of what the money may actually be spent on, read off the
-- NOFO's own allowable-costs section. Sibling to description_brief (0069/0071): grant-level
-- not client-level, enrichment only, generated by a bounded hourly sweep rather than in the
-- ingest path (app/api/cron/ingest/route.ts and lib/grants/pipeline.ts are protected).
--
-- WHY jsonb AND NOT text[]. Every line carries the verbatim NOFO span it came from, so the
-- unit of storage is a PAIR, not a string. The quote is what makes the list checkable after
-- the fact: a reader who doubts a line can find it in raw_text. A text[] of rendered lines
-- would throw away the only thing that makes this trustworthy.
--
--   { "items": [ { "line": "...", "quote": "..." } ], "reason": null | "no_section" | ... }
--
-- THE reason FIELD EXISTS BECAUSE AN EMPTY LIST IS AMBIGUOUS. items: [] can mean the NOFO
-- has no allowable-costs section, or that it has one and every line failed quote
-- verification, or that the grant has no raw_text to verify against. Those are three
-- different problems -- one is the NOFO's, one is the model's, one is ours -- and a bare
-- empty array cannot tell them apart. #312 already cost us that lesson: a single `skipped`
-- counter conflated "nothing to paraphrase" with "the write failed", and the trend across
-- hours was the only way to notice. Store the reason.
--
-- Values: null (items present), 'no_section', 'no_raw_text', 'all_dropped'.
--
-- NOT CLIENT-VISIBLE ON ARRIVAL. Rendering is gated behind ALLOWABLE_USES_CLIENT_VISIBLE
-- (default off) for a staff-only first week while the drop rate is observed. Nothing here
-- depends on that flag -- the column fills either way and the gate is application-layer.

begin;

alter table grants add column if not exists allowable_uses jsonb;
-- Last SUCCESSFUL generation, where "successful" includes a verified-empty result: a NOFO
-- with no allowable-costs section is a real answer, not a failure, and must not be
-- re-claimed hourly forever. Mirrors description_brief_at.
alter table grants add column if not exists allowable_uses_at timestamptz;
-- Attempt counter, same three-strike shape as 0071. A grant whose text can never yield a
-- verifiable list costs 3 Anthropic calls total instead of one an hour indefinitely.
alter table grants add column if not exists allowable_uses_attempts integer not null default 0;

-- The sweep's claim: `allowable_uses is null` AND `attempts < 3`, oldest ingest first.
--
-- THE PREDICATE MUST MATCH THE CLAIM, INCLUDING THE ATTEMPT CAP. 0071 had to widen
-- grants_description_brief_pending_idx for exactly this reason -- an index predicate that
-- omits the cap makes the planner scan every unwritten row, including the parked ones the
-- cap exists to stop touching. Raising MAX_ALLOWABLE_USES_ATTEMPTS in the application
-- REQUIRES a new migration widening this index to match.
create index if not exists grants_allowable_uses_pending_idx
  on grants (ingested_at)
  where allowable_uses is null and allowable_uses_attempts < 3;

-- Ordered scan for any future recut phase (the equivalent of 0071's thin-brief requeue).
-- Added now rather than later because the recut is the shape this sweep will eventually
-- need once the normalization decision is settled from real drop-rate data, and adding an
-- index to a table under an hourly sweep is cheaper before the column has rows than after.
create index if not exists grants_allowable_uses_recut_idx
  on grants (allowable_uses_at)
  where allowable_uses is not null;

insert into schema_migrations (version) values ('0072_grants_allowable_uses') on conflict do nothing;

commit;
